# Generated by Django 5.2.4 on 2025-07-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20250731_0745'),
        ('recommendation', '0005_auto_20250731_0750'),
    ]

    operations = [
    ]
